import { default as grays } from './grays';
import { default as indigos } from './indigos';
import { default as cyans } from './cyans';
import { default as greens } from './greens';
import { default as reds } from './reds';
import { default as teals } from './teals';
import { default as pinks } from './pinks';
import { default as yellows } from './yellows';
import { default as oranges } from './oranges';
import { default as blues } from './blues';
import { default as purples } from './purples';
import { default as common } from './common';
import { default as theme } from './theme';
export { grays, indigos, cyans, greens, reds, teals, pinks, yellows, oranges, blues, purples, common, theme };
