export declare function getServerByUrl(_url: any): any;
export declare function getServerWithProtocol(_url: any): string;
export declare function isSameServer(_url1: any, _url2: any): boolean;
export declare function getDomain(url: any): string;
export declare function isSameDomain(url1: any, url2: any): boolean;
export declare function isOrgOnline(_url: any): boolean;
export declare function isOnline(_url: any): boolean;
export declare function isArcGIScom(_url: any): boolean;
export declare function getStandardPortalUrl(_portalUrl: any): any;
export declare function isSamePortalUrl(_portalUrl1: any, _portalUrl2: any): boolean;
export declare function addProtocol(url: any): any;
export declare function getProtocol(url: any): string;
export declare function updateUrlProtocolByOtherUrl(url: any, otherUrl: any): any;
export declare function removeProtocol(_url: any): any;
export declare function setHttpProtocol(_url: any): any;
export declare function setHttpsProtocol(_url: any): any;
export declare function setProtocol(_url: any, protocol: any): any;
export declare function getSharingUrl(_portalUrl: any): string;
export declare function getOAuth2Url(_portalUrl: any): string;
export declare function getAppIdUrl(_portalUrl: any, _appId: any): string;
export declare function getSignInUrl(_portalUrl: any): string;
export declare function getBaseSearchUrl(_portalUrl: any): string;
export declare function getBaseItemUrl(_portalUrl: any): string;
export declare function getItemUrl(_portalUrl: any, _itemId: any): string;
export declare function getItemDataUrl(_portalUrl: any, _itemId: any): string;
export declare function getItemGroupsUrl(_portalUrl: any, _itemId: any): string;
export declare function getGenerateTokenUrl(_portalUrl: any): string;
export declare function getItemDetailsPageUrl(_portalUrl: any, _itemId: any): string;
export declare function getUserProfilePageUrl(_portalUrl: any, _user: any): string;
export declare function getBaseGroupUrl(_portalUrl: any): string;
export declare function getPortalSelfInfoUrl(_portalUrl: any): string;
export declare function getCommunitySelfUrl(_portalUrl: any): string;
export declare function getBaseUserUrl(_portalUrl: any): string;
export declare function getUserUrl(_portalUrl: any, _userId: any): string;
export declare function getUserTagsUrl(_portalUrl: any, _userId: any): string;
export declare function getUserThumbnailUrl(portalUrl: any, userId: any, thumbnail: any): string;
export declare function getContentUrl(_portalUrl: any): string;
export declare function getUserContentUrl(_portalUrl: any, _user: any, _folderId?: any): string;
export declare function getUserContentItemUrl(_portalUrl: any, _user: any, _itemId: any): string;
export declare function getItemResourceUrl(_portalUrl: any, _itemId: any, _customResUrl: any): string;
export declare function getAddItemUrl(_portalUrl: any, _user: any, _folderId: any): string;
export declare function getDeleteItemUrl(_portalUrl: any, _user: any, _itemId: any): string;
export declare function getUserItemsUrl(_portalUrl: any, _user: any, _folderId?: any): string;
export declare function getUpdateItemUrl(_portalUrl: any, _user: any, _itemId: any, _folderId: any): string;
export declare function shareItemUrl(_portalUrl: any, _user: any, _itemId: any, _folderId: any): string;
export declare function getHomeIndexUrl(_portalUrl: any): string;
export declare function getHomeMapViewerUrl(_portalUrl: any, /* optional */ itemId: any): string;
export declare function getHomeSceneViewerUrl(_portalUrl: any, /* optional */ itemId: any): string;
export declare function getHomeGalleryUrl(_portalUrl: any): string;
export declare function getHomeGroupsUrl(_portalUrl: any): string;
export declare function getHomeMyContentUrl(_portalUrl: any): string;
export declare function getHomeMyOrganizationUrl(_portalUrl: any): string;
export declare function getHomeUserUrl(_portalUrl: any): string;
export declare function getPortalHelpUrl(_portalUrl: any, locale: any): string;
export declare function getPortalAdminHelpUrl(_portalUrl: any, locale: any): string;
export declare function getPortalProxyUrl(_portalUrl: any): string;
export declare function getOAuth2SignOutUrl(_portalUrl: any): string;
export declare function getNewPrintUrl(_portalUrl: any): string;
export declare function getSwitchAccoutnsUrl(_portalUrl: any, client_id: any, /*optional*/ redirect_uri: any): string;
